services:
  djangoapp:
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./data/web/static:/data/web/static/
      - ./data/web/media:/data/web/media/
    env_file:
      - ./env/.env
    depends_on:
      - psql
  
  psql:
    image: postgres:13-alpine
    volumes:
      - ./data/postgres/data:/var/lib/postgresql/data/
    env_file:
      - ./env/.env