# Generated by Django 5.2.4 on 2025-07-26 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Árvore',
                'verbose_name_plural': 'Árvores',
            },
        ),
        migrations.CreateModel(
            name='PlantedTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('planted_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(decimal_places=6, default='0.0', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, default='0.0', max_digits=9)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trees.tree')),
            ],
            options={
                'verbose_name': 'Árvore Plantada',
                'verbose_name_plural': 'Árvores Plantadas',
            },
        ),
    ]
