# Generated by Django 5.1.4 on 2025-07-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlantedTree',
        ),
    ]
